#pragma once


#ifndef ONESHOT_TAP_TOGGLE
#define ONESHOT_TAP_TOGGLE 2
#endif // !ONESHOT_TAP_TOGGLE

#ifndef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 3000
#endif// !ONESHOT_TIMEOUT

#ifndef QMK_KEYS_PER_SCAN
#define QMK_KEYS_PER_SCAN 4
#endif // !QMK_KEYS_PER_SCAN

#define MACRO_TIMER 5
#define USB_MAX_POWER_CONSUMPTION 100

#if defined(UNICODE_ENABLE) || defined(UNICODEMAP_ENABLE)
#define UNICODE_SELECTED_MODES UC_WINC, UC_LNX
#endif
